# Change these first
owner: ohelitco # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Muysc
    url: https://muysc.ohelit.co
  - name: CA
    url: https://ca.ohelit.co/api
  - name: reportes
    url: https://repository.ohelit.co
  - name: Aut
    url: https://auth.ohelit.co/auth/
  - name: Class
    url: https://class.ohelit.co/

assignees:
  - ohelitco

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: estado.ohelit.co
  # baseUrl: /your-repo-name
  logoUrl: https://ohelit.co/wp-content/uploads/2019/08/Ohelitverde.png
  name: Ohelit Status
  introTitle: "Estado de servicios Ohelit"
  introMessage: En este sitio encuentras la información de estado actual de todos nuestros servicios WEB públicos. Notas: •	Este sitio de estado, monitorea en tiempo real cada uno de nuestros servicios WEB públicos.  •	El periodo de actualización promedio es de 8 minutos. •	Puedes ver los incidentes activos, avances y estados de los mismo.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
